Initial commit for HMOS EasyGuideView
applibgroup/EasyGuideView pull request #1
Opened 2021-12-15 12:38 UTC by Jobin1000

2021-12-16 12:28 UTC, samuel-abhishek commented on LICENSE
> +   Copyright [yyyy] [name of copyright owner]
Please retain the same License copy of the Base library.

2021-12-16 12:36 UTC, samuel-abhishek commented on README.md
> +		implementation project(':library')
this library name will give an issue during maven release. Change the library module name to "easyguideview"

2021-12-16 12:39 UTC, samuel-abhishek commented on entry/src/main/java/com/yuyh/easyguideview/slice/MainAbilitySlice.java
> +                .addMessage("Menu Content", 14)
Instead of using hardcoded strings. Add these strings in String resource files and access them.

2021-12-16 12:40 UTC, samuel-abhishek commented on entry/src/main/resources/base/element/string.json
> +      "value": "entry_MainAbility"
Please modify the default string values from generic values to appropriate values based on the library. If the strings are not required, you can delete them

2021-12-16 12:54 UTC, samuel-abhishek commented on library/src/main/java/com/yuyh/library/EasyGuide.java
> +                tvMsg.setTextSize(50);
textSize should not hardcoded. It should depend on message.textSize value. Please check the base lib implementation

2021-12-16 12:56 UTC, samuel-abhishek commented on library/src/main/java/com/yuyh/library/EasyGuide.java
> +            tvConfirm.setTextColor(hmosColor1);
setTextSize must not be hardcode value. It should depend on mConfim.textSize value

2021-12-16 13:08 UTC, samuel-abhishek commented on library/src/main/java/com/yuyh/library/EasyGuide.java
public Builder addHightLightArea(HighlightArea area); - public method api is missing in hmos code. Please check

2021-12-16 13:11 UTC, samuel-abhishek commented on library/src/main/java/com/yuyh/library/EasyGuide.java
> +/*
Applibgroup copyright should not be added for any of the lib files unless the files which are implemented from scratch. Please check and correct this for all lib files.

2021-12-16 13:34 UTC, samuel-abhishek requested changes
Please check & handle the review comments

2021-12-17 10:58 UTC, samuel-abhishek approved these changes
Okay

2021-12-20 03:13 UTC, sharathks84 approved these changes
okay, approved

2021-12-20 09:25 UTC, Gleelakrishna approved these changes
ok

2021-12-20 09:25 UTC, merged